[package]

name = "osauth"
description = "Asynchronous OpenStack session and authentication"
version = "0.2.5"
authors = ["Dmitry Tantsur <divius.inside@gmail.com>"]
homepage = "https://github.com/dtantsur/rust-osauth"
repository = "https://github.com/dtantsur/rust-osauth"
documentation = "https://docs.rs/osauth"
readme = "README.md"
license = "Apache-2.0"
keywords = ["api", "cloud", "openstack"]
categories = ["api-bindings"]
edition = "2018"

[features]

default = ["native-tls", "stream"]
native-tls = ["reqwest/default-tls"]
rustls = ["reqwest/rustls-tls"]
stream = ["async-stream", "futures"]

[dependencies]

async-stream = { version = "^0.2", optional = true }
async-trait = "^0.1"
chrono = { version = "^0.4", features = ["serde"] }
dirs = "^2.0"
futures = { version = "^0.3", optional = true }
log = "^0.4"
osproto = "^0.2.0"
reqwest = { version = "^0.10", default-features = false, features = ["gzip", "json", "stream"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_yaml = "^0.8"

[dev-dependencies]

env_logger = "^0.7"
tokio = { version = "^0.2.0", features = ["macros"] }

[lib]

name = "osauth"
path = "src/lib.rs"

[badges]
travis-ci = { repository = "dtantsur/rust-osauth" }
