name: Functional
on:
  - pull_request
jobs:
  functional:
    strategy:
      fail-fast: false
      matrix:
        name: ["master"]
        openstack_version: ["master"]
        ubuntu_version: ["20.04"]
        include:
          - name: "xena"
            openstack_version: "stable/xena"
            ubuntu_version: "20.04"
          - name: "wallaby"
            openstack_version: "stable/wallaby"
            ubuntu_version: "20.04"
          - name: "victoria"
            openstack_version: "stable/victoria"
            ubuntu_version: "20.04"
          - name: "ussuri"
            openstack_version: "stable/ussuri"
            ubuntu_version: "18.04"
          - name: "train"
            openstack_version: "stable/train"
            ubuntu_version: "18.04"
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Deploy OpenStack ${{ matrix.name }} and run examples
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.6
        with:
          branch: ${{ matrix.openstack_version }}
          enabled_services: swift
          log_dir: /tmp/devstack-logs
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build the project
        run: cargo build --release --all-features --all-targets
      - name: Run tests
        run: ./tools/test-functional.sh
      - name: Generate logs
        run: ./tools/collect-logs.sh
        if: always()
      - name: Upload logs artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: functional-${{ matrix.name }}
          path: /tmp/devstack-logs/*
